name: doberman
version: 2.6.2
summary: Statistical Analysis of OIL
description: Statistical Analysis of OIL (oil-stats, crude-analysis, refinery, filing-station)
confinement: strict

apps:
  oil-stats:
    command: stats
    plugs: [network-bind]
  oil-cookie:
    command: oil-cookie
    plugs: [network-bind]
  crude-analysis:
    command: crude-analysis
    plugs: [network-bind]
  refinery:
    command: refinery
    plugs: [network-bind]
  filing-station:
    command: filing-station

parts:
  script:
    plugin: python2
    source: .
    build-packages:
      - python-yaml
